#!/bin/python

from utils.taskwarrior import list_domains
import argparse
import sys

def main():
    parser= argparse.ArguementParser(description='kanbanwarrior')

if __name__ == '__main__':
    main()
