#!/bin/python

from kanbanwarrior.cli import dispatch_action
from argparse import ArgumentParser


def main():
    parser = ArgumentParser(description='kanbanwarrior')
    parser.add_argument(dest='action',
                        help="one of: domains, projects, server")
    args = parser.parse_args()

    dispatch_action(args.action, parser)


if __name__ == '__main__':
    main()
