#!/bin/sh

PROJECTDIR=${PROJECTDIR:-$(pwd)}

export TESTDIR="$PROJECTDIR/tests"
export TASKRC="$PROJECTDIR/tests/.taskrc"
export PYTHONPATH="$PROJECTDIR"

taskrc=$(cat <<EOF
confirmation=no
data.location=$TESTDIR/.task
EOF
)

echo "$taskrc" > "$TESTDIR/.taskrc"
rm -fr "$TESTDIR"/.task/*

python "$TESTDIR/acceptance.py"
