#!/bin/sh

PROJECTDIR=${PROJECTDIR:-$(pwd)}

taskrc=$(cat <<EOF
confirmation=no
data.location=.task
EOF
)

echo "$taskrc" > .taskrc
rm -fr .task/*

export TESTDIR="$PROJECTDIR/tests"
export TASKRC="$PROJECTDIR/tests/.taskrc"
export PYTHONPATH="$PROJECTDIR"

python acceptance.py
